const mongoose=require('mongoose');
mongoose.connect('mongodb://localhost:27017/users',
(err) => {
 if(err) console.log("user page error") 
 else console.log("mongdb is connected");
});
var conn=mongoose.Collection;
var userSchema=new mongoose.Schema(
    {
        submission_id:{
            type:String,
            required:true
        },
        name:{
            type:String,
            required:true
        },
        birthdate:{
            type:String,
            required:true
        },
        date:{
            type:Date,
            default:Date.now
        },
        age:{
            type:String
            
        },
        gender:{
            type:String,
            required:true
        },email79:{
            type:String,
            required:true
        },theresponses:{
            type:String,
            required:true
        },q1:{
            type:String,
            required:true
        },q2:{
            type:String,
            required:true
        },q3:{
            type:String,
            required:true
        },q4:{
            type:String,
            required:true
        },q5:{
            type:String,
            required:true
        },q6:{
            type:String,
            required:true
        },q7:{
            type:String,
            required:true
        },q8:{
            type:String,
            required:true
        },q9:{
            type:String,
            required:true
        },q10:{
            type:String,
            required:true
        },q11:{
            type:String,
            required:true
        },q12:{
            type:String,
            required:true
        },q13:{
            type:String,
            required:true
        },q14:{
            type:String,
            required:true
        },q15:{
            type:String,
            required:true
        },q16:{
            type:String,
            required:true
        },q17:{
            type:String,
            required:true
        },q18:{
            type:String,
            required:true
        },q20:{
            type:String,
            required:true
        }
        ,q21:{
            type:String,
            required:true
        }
        ,q22:{
            type:String,
            required:true
        }
        ,q23:{
            type:String,
            required:true
        },q24:{
            type:String,
            required:true
        },q25:{
            type:String,
            required:true
        },q26:{
            type:String,
            required:true
        },q27:{
            type:String,
            required:true
        },q28:{
            type:String,
            required:true
        },q29:{
            type:String,
            required:true
        },q30:{
            type:String,
            required:true
        },q31:{
            type:String,
            required:true
        },q32:{
            type:String,
            required:true
        },q33:{
            type:String,
            required:true
        }
        ,star1:{
            type:String,
            required:true
        },star2:{
            type:String,
            required:true
        },q34:{
            type:String,
            required:true
        },q35:{
            type:String,
            required:true
        },q36:{
            type:String,
            required:true
        },q37:{
            type:String,
            required:true
        },q38:{
            type:String,
            required:true
        },q39:{
            type:String,
            required:true
        },q40:{
            type:String,
            required:true
        },q41:{
            type:String,
            required:true
        },q42:{
            type:String,
            required:true
        },q43:{
            type:String,
            required:true
        },q44:{
            type:String,
            required:true
        },q45:{
            type:String,
            required:true
        },q46:{
            type:String,
            required:true
        }

        

    }
);
var userModel=mongoose.model('user',userSchema);
module.exports=userModel;